[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-da-network-core"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
cached                   = { workspace = true }
either                   = { default-features = false, version = "1.13.0" }
fixed                    = { default-features = false, features = ["serde-str"], version = "1" }
futures                  = { default-features = false, version = "0.3" }
indexmap                 = { default-features = false, version = "2.2" }
kzgrs-backend            = { workspace = true }
libp2p                   = { features = ["macros", "quic", "tokio"], workspace = true }
libp2p-stream            = "0.3.0-alpha"
log                      = "0.4"
nomos-core               = { workspace = true }
nomos-da-messages        = { workspace = true }
nomos-utils              = { workspace = true }
rand                     = { default-features = false, version = "0.8" }
serde                    = { default-features = false, version = "1.0" }
serde_with               = { workspace = true }
subnetworks-assignations = { workspace = true }
thiserror                = "1.0"
tokio                    = { version = "1" }
tokio-stream             = { default-features = false, version = "0.1" }
tracing                  = { workspace = true }
tracing-subscriber       = { default-features = false, version = "0.3.18" }

[dev-dependencies]
bincode            = "1.3"
kzgrs              = { workspace = true }
kzgrs-backend      = { features = ["testutils"], workspace = true }
libp2p             = { features = ["plaintext", "yamux"], workspace = true }
libp2p-swarm-test  = { default-features = false, features = ["tokio"], version = "0.5.0" }
nomos-utils        = { workspace = true }
rstest             = { default-features = false, version = "0.25" }
tokio              = { default-features = false, version = "1" }
tracing-subscriber = { default-features = false, features = ["env-filter", "fmt", "std"], version = "0.3" }
