[package]
edition           = "2024"
license.workspace = true
name              = "pol"
version           = "0.1.0"

[dependencies]
circuits-prover       = { workspace = true }
circuits-utils        = { workspace = true }
groth16               = { workspace = true, features = ["deser"] }
num-bigint            = "0.4"
num-traits            = "0.2.19"
pol-witness-generator = { workspace = true }
serde                 = { version = "1.0", features = ["derive"] }
serde_json            = { version = "1.0" }
thiserror             = "2.0"

[dev-dependencies]

[lints]
workspace = true
