[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-storage"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait        = "0.1"
bytes              = { workspace = true }
cryptarchia-engine = { workspace = true }
libp2p-identity    = { default-features = false, features = ["serde"], version = "0.2" }
multiaddr          = { default-features = false, version = "0.18" }
nomos-core         = { workspace = true }
overwatch          = { workspace = true }
rocksdb            = { default-features = false, features = ["bindgen-runtime"], optional = true, version = "0.24" }
serde              = { default-features = false, version = "1.0" }
thiserror          = "1.0"
tokio              = { default-features = false, version = "1" }
tracing            = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio    = { default-features = false, version = "1" }

[features]
default         = []
mock            = []
rocksdb-backend = ["dep:rocksdb"]

[[bin]]
name              = "rocks"
path              = "src/bin/rocks.rs"
required-features = ["rocksdb-backend"]
