[package]
edition           = "2024"
license.workspace = true
name              = "circuits-prover"
version           = "0.1.0"

[dependencies]
circuits-utils = { workspace = true }
tempfile       = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["circuits-utils", "tempfile"] # machete hallucinations
