[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-node"
version = "0.1.0"

[package.metadata.cargo-machete]
# False positives.
ignored = [
  # Required by Overwatch's `#[derive_services]` macro.
  "tokio",
  # Required by `wait_until_services_are_ready` macro.
  "futures",
]

[lints]
workspace = true

[dependencies]
async-trait              = "0.1"
bytes                    = { workspace = true }
chain-service            = { workspace = true, features = ["libp2p"] }
clap                     = { version = "4", features = ["derive", "env"] }
color-eyre               = "0.6.0"
futures                  = "0.3"
hex                      = "0.4.3"
http                     = "0.2.9"
kzgrs-backend            = { workspace = true }
nomos-api                = { workspace = true }
nomos-blend-service      = { workspace = true, features = ["libp2p"] }
nomos-core               = { workspace = true }
nomos-da-indexer         = { workspace = true, features = ["rocksdb-backend"] }
nomos-da-messages        = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-da-network-service = { workspace = true }
nomos-da-sampling        = { workspace = true, features = ["rocksdb-backend"] }
nomos-da-verifier        = { workspace = true, features = ["libp2p", "rocksdb-backend"] }
nomos-http-api-common    = { workspace = true }
nomos-libp2p             = { workspace = true }
nomos-membership         = { workspace = true }
nomos-mempool            = { workspace = true, features = ["libp2p", "mock"] }
nomos-network            = { workspace = true, features = ["libp2p"] }
nomos-sdp                = { workspace = true }
nomos-storage            = { workspace = true, features = ["rocksdb-backend"] }
nomos-system-sig         = { workspace = true }
nomos-time               = { workspace = true, features = ["ntp", "serde"] }
nomos-tracing            = { workspace = true }
nomos-tracing-service    = { workspace = true }
overwatch                = { workspace = true }
serde                    = "1"
serde_yaml               = "0.9"
services-utils           = { workspace = true }
subnetworks-assignations = { workspace = true }
tokio                    = "1"
tracing                  = { workspace = true }

# openapi related dependencies
utoipa            = { workspace = true }
utoipa-swagger-ui = { workspace = true }

# axum related dependencies
axum       = { version = "0.6" }
hyper      = { version = "0.14", features = ["full"] }
time       = "0.3"
tower-http = { version = "0.4", features = ["cors", "trace"] }

[features]
default         = ["tracing"]
instrumentation = []
testing         = []
tracing         = []
