[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-node"
version = "0.1.0"

[package.metadata.cargo-machete]
# False positives.
ignored = [
  # Required by `wait_until_services_are_ready` macro.
  "futures",
]

[lints]
workspace = true

[dependencies]
async-trait              = "0.1"
broadcast-service        = { workspace = true }
bytes                    = { workspace = true }
chain-service            = { workspace = true }
clap                     = { default-features = false, features = ["derive", "env", "std"], version = "4" }
color-eyre               = { default-features = false, version = "0.6.0" }
futures                  = { default-features = false, version = "0.3" }
hex                      = { default-features = false, version = "0.4.3" }
http                     = "0.2.9"
kzgrs-backend            = { workspace = true }
nomos-api                = { workspace = true }
nomos-blend-service      = { workspace = true }
nomos-core               = { workspace = true }
nomos-da-messages        = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-da-network-service = { workspace = true }
nomos-da-sampling        = { features = ["libp2p", "rocksdb-backend"], workspace = true }
nomos-da-verifier        = { features = ["libp2p"], workspace = true }
nomos-http-api-common    = { workspace = true }
nomos-libp2p             = { workspace = true }
nomos-membership         = { workspace = true }
nomos-mempool            = { workspace = true }
nomos-network            = { workspace = true }
nomos-sdp                = { workspace = true }
nomos-storage            = { workspace = true }
nomos-system-sig         = { workspace = true }
nomos-time               = { features = ["ntp", "serde"], workspace = true }
nomos-tracing            = { workspace = true }
nomos-tracing-service    = { workspace = true }
num-bigint               = { version = "0.4", default-features = false }
overwatch                = { workspace = true }
serde                    = { default-features = false, version = "1" }
serde_yaml               = "0.9"
services-utils           = { workspace = true }
subnetworks-assignations = { workspace = true }
tokio                    = "1"
tracing                  = { workspace = true }

# openapi related dependencies
utoipa            = { workspace = true }
utoipa-swagger-ui = { features = ["axum"], workspace = true }

# axum related dependencies
axum       = { default-features = false, features = ["http1", "http2", "json", "query", "tokio"], version = "0.7.5" }
time       = { default-features = false, version = "0.3" }
tower      = { default-features = false, features = ["limit"], version = "0.4" }
tower-http = { default-features = false, features = ["cors", "limit", "timeout", "trace"], version = "0.5" }

[features]
default         = ["tracing"]
instrumentation = []
testing         = []
tracing         = []
