[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-sdp"
version = "0.1.0"

[dependencies]
async-trait    = "0.1"
futures        = "0.3"
nomos-core     = { workspace = true }
nomos-sdp-core = { workspace = true }
overwatch      = { workspace = true }
thiserror      = "1"
tokio          = { version = "1", features = ["macros", "sync"] }
tokio-stream   = "0.1"
tracing        = { version = "0.1", features = ["attributes"] }
