[package]
edition = { workspace = true }
license = { workspace = true }
name    = "nomos-sdp"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait  = "0.1"
futures      = { default-features = false, version = "0.3" }
nomos-core   = { workspace = true }
overwatch    = { workspace = true }
thiserror    = "1"
tokio        = { default-features = false, version = "1" }
tokio-stream = { default-features = false, version = "0.1" }
tracing      = { workspace = true }
