[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-sdp"
version = "0.1.0"

[dependencies]
async-trait    = "0.1"
futures        = "0.3"
nomos-sdp-core = { workspace = true }
overwatch      = { workspace = true }
services-utils = { workspace = true }
tokio          = { version = "1", features = ["macros", "sync"] }
tracing        = { version = "0.1", features = ["attributes"] }
