[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-mempool"
version = "0.1.0"

[package.metadata.cargo-machete]
# False positives.
ignored = [
  # Required by `utoipa`.
  "serde_json",
]

[lints]
workspace = true

[dependencies]
async-trait           = "0.1"
futures               = "0.3"
kzgrs-backend         = { workspace = true }
linked-hash-map       = { version = "0.5.6", optional = true, features = ["serde_impl"] }
nomos-core            = { workspace = true }
nomos-da-network-core = { workspace = true }
nomos-da-sampling     = { workspace = true, features = ["rocksdb-backend"] }
nomos-da-verifier     = { workspace = true, features = ["rocksdb-backend"] }
nomos-network         = { workspace = true }
overwatch             = { workspace = true }
rand                  = { workspace = true }
serde                 = { version = "1.0", features = ["derive"] }
serde_json            = { version = "1", optional = true }
services-utils        = { workspace = true }
thiserror             = "1.0"
tokio                 = { version = "1", features = ["macros", "sync"] }
tokio-stream          = "0.1"
tracing               = { workspace = true }
utoipa                = { workspace = true, optional = true }

[dev-dependencies]
nomos-mempool         = { path = ".", features = ["mock"] }
nomos-tracing-service = { workspace = true }
nomos-utils           = { workspace = true }
overwatch-derive      = { workspace = true }
tokio                 = { version = "1", features = ["full"] }

[features]
default         = []
instrumentation = []
libp2p          = ["nomos-network/libp2p"]
mock            = ["dep:linked-hash-map", "nomos-core/mock", "nomos-network/mock"]

# enable to help generate OpenAPI
openapi = ["dep:serde_json", "dep:utoipa"]
