[package]
edition = "2021"
license = { workspace = true }
name    = "executor-http-client"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
common-http-client    = { workspace = true }
futures               = { default-features = false, version = "0.3.31" }
nomos-core            = { workspace = true }
nomos-http-api-common = { workspace = true }
reqwest               = { workspace = true }
serde                 = { default-features = false, version = "1.0" }
