[package]
edition           = "2024"
license.workspace = true
name              = "zksign"
version           = "0.1.0"

[dependencies]
circuits-prover   = { workspace = true }
circuits-utils    = { workspace = true }
groth16           = { features = ["deser"], workspace = true }
serde             = { features = ["derive"], version = "1.0" }
serde_json        = { workspace = true }
thiserror         = { workspace = true }
witness-generator = { workspace = true }

[dev-dependencies]
num-bigint = "0.4"
poseidon2  = { workspace = true }
rand       = "0.8"

[lints]
workspace = true
