[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-da-indexer"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait           = "0.1"
bytes                 = { workspace = true }
cryptarchia-consensus = { workspace = true }
futures               = "0.3"
kzgrs-backend         = { workspace = true }
nomos-core            = { workspace = true }
nomos-da-sampling     = { workspace = true }
nomos-da-verifier     = { workspace = true }
nomos-mempool         = { workspace = true }
nomos-storage         = { workspace = true }
nomos-time            = { workspace = true }
nomos-tracing         = { workspace = true }
overwatch             = { workspace = true }
rand                  = "0.8"
serde                 = { version = "1.0", features = ["derive"] }
services-utils        = { workspace = true }
tokio                 = { version = "1", features = ["sync"] }
tokio-stream          = "0.1.15"
tracing               = { workspace = true }

[features]
rocksdb-backend = ["nomos-storage/rocksdb-backend"]
