[package]
edition           = "2024"
license.workspace = true
name              = "circuits-pol"
version           = "0.1.0"

[dependencies]
circuits-utils = { workspace = true }
tempfile       = { workspace = true }

[lints]
workspace = true
