[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-network"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait      = "0.1"
chrono           = { version = "0.4", optional = true }
cryptarchia-sync = { workspace = true }
futures          = "0.3"
nomos-core       = { workspace = true }
nomos-libp2p     = { workspace = true, optional = true }
overwatch        = { workspace = true }
rand             = { workspace = true, optional = true }
serde            = { version = "1.0", features = ["derive"] }
tokio            = { version = "1", features = ["macros", "sync"] }
tokio-stream     = "0.1"
tracing          = { workspace = true }
utoipa           = { workspace = true, optional = true }

[dev-dependencies]
tokio              = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
default = []
libp2p  = ["cryptarchia-sync/libp2p", "dep:nomos-libp2p", "dep:rand"]
mock    = ["dep:chrono", "dep:rand"]
openapi = ["dep:utoipa"]
