[package]
edition = { workspace = true }
license = { workspace = true }
name    = "subnetworks-assignations"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
counter         = "0.6"
libp2p-identity = { default-features = false, features = ["peerid", "serde"], version = "0.2" }
nomos-core      = { workspace = true }
nomos-utils     = { workspace = true }
rand            = { default-features = false, features = ["std_rng"], workspace = true }
serde           = { default-features = false, version = "1" }

[dev-dependencies]
divan           = { default-features = false, version = "0.1" }
libp2p-identity = { default-features = false, features = ["peerid", "rand"], version = "0.2" }
nomos-utils     = { features = ["rng"], workspace = true }
rand            = { default-features = false, features = ["small_rng", "std"], workspace = true }

[[bench]]
harness = false
name    = "historic_aware_refill"
