[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-tracing-service"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait        = "0.1"
nomos-tracing      = { workspace = true }
overwatch          = { workspace = true }
serde              = { version = "1.0", features = ["derive"] }
tracing            = { workspace = true }
tracing-appender   = "0.2"
tracing-subscriber = { version = "0.3", features = ["json", "registry"] }
