[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-system-sig"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-ctrlc = "1.2"
async-trait = "0.1"
overwatch   = { workspace = true }
tracing     = "0.1"
