[package]
edition = { workspace = true }
license = { workspace = true }
name    = "nomos-system-sig"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-ctrlc = "1.2"
async-trait = "0.1"
overwatch   = { workspace = true }
tracing     = { default-features = false, version = "0.1" }
