[package]
edition           = "2024"
license.workspace = true
name              = "groth16"
version           = "0.1.0"

[dependencies]
ark-bn254   = { default-features = false, features = ["curve"], version = "0.4" }
ark-ec      = "0.4"
ark-ff      = { version = "0.4" }
ark-groth16 = { default-features = false, features = ["std"], version = "0.4" }
hex         = { version = "0.4", default-features = false, features = ["alloc"], optional = true }
num-bigint  = { version = "0.4", default-features = false, optional = true }
serde       = { default-features = false, optional = true, features = ["derive"], version = "1.0" }
serde_json  = { default-features = false, optional = true, version = "1.0", features = ["alloc"] }
thiserror   = { default-features = false, optional = true, version = "2.0" }

[dev-dependencies]
serde_json = { default-features = false, features = ["alloc"], version = "1.0" }

[lints]
workspace = true

[features]
default = []
deser   = ["dep:hex", "dep:num-bigint", "dep:serde", "dep:serde_json", "dep:thiserror"]
