[package]
edition           = "2024"
license.workspace = true
name              = "groth16"
version           = "0.1.0"

[dependencies]
ark-bn254   = "0.4"
ark-ec      = "0.4"
ark-ff      = { version = "0.4" }
ark-groth16 = "0.4"
hex         = { version = "0.4", optional = true }
num-bigint  = { version = "0.4", optional = true }
serde       = { version = "1.0", optional = true, features = ["derive"] }
serde_json  = { version = "1.0", optional = true }
thiserror   = { version = "2.0", optional = true }

[dev-dependencies]
serde_json = "1.0"

[lints]
workspace = true

[features]
default = []
deser   = ["hex", "num-bigint", "serde", "serde_json", "thiserror"]
