[package]
edition           = "2024"
license.workspace = true
name              = "groth16"
version           = "0.1.0"

[dependencies]
ark-bn254   = "0.5"
ark-ec      = "0.5"
ark-groth16 = "0.5"
serde       = { version = "1.0", optional = true, features = ["derive"] }
serde_json  = { version = "1.0", optional = true }
thiserror   = { version = "2.0", optional = true }

[dev-dependencies]
serde_json = "1.0"

[lints]
workspace = true

[features]
default = []
deser   = ["serde", "serde_json", "thiserror"]
