[package]
edition = { workspace = true }
license = { workspace = true }
name    = "groth16"
version = "0.1.0"

[dependencies]
ark-bn254     = { default-features = false, features = ["curve"], version = "0.4" }
ark-ec        = "0.4"
ark-ff        = { version = "0.4" }
ark-groth16   = { default-features = false, features = ["std"], version = "0.4" }
ark-serialize = { default-features = false, version = "0.4.2" }
generic-array = { default-features = false, version = "1.2" }
hex           = { default-features = false, features = ["alloc"], optional = true, version = "0.4" }
num-bigint    = { default-features = false, version = "0.4" }
serde         = { default-features = false, features = ["derive"], optional = true, version = "1.0" }
serde_json    = { default-features = false, features = ["alloc"], optional = true, version = "1.0" }
thiserror     = { default-features = false, version = "2.0" }

[dev-dependencies]
bincode    = { default-features = false, version = "1.3" }
serde_json = { default-features = false, features = ["alloc"], version = "1.0" }

[lints]
workspace = true

[features]
default = []
deser   = ["dep:hex", "dep:serde", "dep:serde_json", "generic-array/serde"]
