[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-time"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait        = "0.1"
cfg_eval           = { optional = true, version = "0.1" }
cryptarchia-engine = { features = ["tokio"], workspace = true }
futures            = { default-features = false, version = "0.3" }
log                = "0.4.22"
nomos-utils        = { optional = true, workspace = true }
overwatch          = { workspace = true }
serde              = { default-features = false, features = ["derive"], optional = true, version = "1.0" }
serde_with         = { optional = true, workspace = true }
sntpc              = { default-features = false, features = ["std", "tokio-socket"], optional = true, version = "0.5" }
thiserror          = { default-features = false, optional = true, version = "2.0" }
time               = { default-features = false, features = ["std"], version = "0.3" }
tokio              = { default-features = false, version = "1" }
tokio-stream       = { default-features = false, version = "0.1" }
tracing            = { default-features = false, version = "0.1" }

[dev-dependencies]
nomos-utils = { workspace = true }

[features]
ntp       = ["dep:sntpc", "dep:thiserror", "tokio/net"]
serde     = ["cryptarchia-engine/serde", "dep:cfg_eval", "dep:nomos-utils", "dep:serde", "dep:serde_with"]
testutils = []
