[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-da-dispersal"
version = "0.1.0"

[dependencies]
async-trait              = "0.1"
futures                  = "0.3"
kzgrs-backend            = { workspace = true }
nomos-core               = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-da-network-service = { workspace = true }
nomos-da-sampling        = { workspace = true }
nomos-da-verifier        = { workspace = true }
nomos-mempool            = { workspace = true, features = ["libp2p"] }
nomos-tracing            = { workspace = true }
nomos-utils              = { workspace = true, features = ["time"] }
overwatch                = { workspace = true }
rand                     = "0.8"
serde                    = { version = "1.0", features = ["derive"] }
serde_with               = { workspace = true }
services-utils           = { workspace = true }
subnetworks-assignations = { workspace = true }
tokio                    = "1"
tokio-stream             = "0.1.15"
tracing                  = { workspace = true }
