[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-da-sampling"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait              = "0.1"
bytes                    = { workspace = true }
futures                  = { default-features = false, version = "0.3" }
hex                      = { default-features = false, version = "0.4.3" }
kzgrs-backend            = { workspace = true }
libp2p-identity          = { version = "0.2" }
nomos-core               = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-da-network-service = { workspace = true }
nomos-storage            = { workspace = true }
nomos-tracing            = { workspace = true }
overwatch                = { workspace = true }
rand                     = { workspace = true }
serde                    = { default-features = false, version = "1.0" }
services-utils           = { workspace = true }
subnetworks-assignations = { workspace = true }
tokio                    = { default-features = false, version = "1" }
tokio-stream             = { default-features = false, version = "0.1.15" }
tracing                  = { workspace = true }

[dev-dependencies]
kzgrs = { workspace = true }

[features]
default         = ["libp2p"]
libp2p          = []
rocksdb-backend = ["nomos-storage/rocksdb-backend"]
