[package]
edition = "2021"
license = { workspace = true }
name    = "cfgsync"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
axum                     = { version = "0.6" }
clap                     = { version = "4", features = ["derive"] }
nomos-blend              = { workspace = true }
nomos-blend-message      = { workspace = true }
nomos-da-dispersal       = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-executor           = { workspace = true }
nomos-libp2p             = { workspace = true }
nomos-membership         = { workspace = true }
nomos-node               = { workspace = true }
nomos-sdp-core           = { workspace = true }
nomos-tracing-service    = { workspace = true }
nomos-utils              = { workspace = true, features = ["time"] }
rand                     = "0.8"
reqwest                  = { workspace = true, features = ["json", "rustls-tls"] }
serde                    = { version = "1", features = ["derive"] }
serde_json               = "1.0"
serde_path_to_error      = "0.1"
serde_with               = { workspace = true }
serde_yaml               = "0.9"
subnetworks-assignations = { workspace = true }
tests                    = { workspace = true }
tokio                    = { version = "1", features = ["rt-multi-thread"] }
tracing                  = { workspace = true }

[dev-dependencies]
futures = "0.3"
