tracing:
  logger: !Stdout
  tracing: None
  filter: None
  metrics: None
  level: DEBUG
network:
  backend:
    host: 0.0.0.0
    port: 3000
    node_key: ea1e1dcc31612bd20987f017f0ca435cd2a59a4bd9fd6e14883b4803ae3b803d
    initial_peers: []
blend:
  backend:
    listening_address: /ip4/127.0.0.1/udp/3001/quic-v1
    node_key: ea1e1dcc31612bd20987f017f0ca435cd2a59a4bd9fd6e14883b4803ae3b803d
    peering_degree: 1
    max_peering_degree: 3
    conn_monitor: null
    minimum_messages_coefficient: 3
    normalization_constant: 1.03
    edge_node_connection_timeout:
      secs: 1
      nanos: 0
  crypto:
    signing_private_key: 32e4b52b78e0e8273f31e2ae0826d09b0348d4c66824af4f51ec4ef338082211
    num_blend_layers: 1
  time:
    # 21,600 blocks * 30s per block * 1s per round = 648,000 rounds
    rounds_per_session: 648000
    rounds_per_interval: 30
    round_duration: [1, 0]
    # Defined in the spec
    rounds_per_observation_window: 30
  scheduler:
    intervals_for_safety_buffer: 100
    message_frequency_per_round: 1.0
    redundancy_parameter: 0
    maximum_release_delay_in_rounds: 3
  membership:
    - id: 12D3KooWKD62Q1nAAMHeV2Cx3rNNMzjgHkTT2edFMzHZ5ur7sGnh
      address: /ip4/127.0.0.1/udp/8720/quic-v1
      public_key: cd81cab2112a1cf8e6d986d53c0ab6c740e3a82dc04e0a6497f62727969fa5fd
    - id: 12D3KooWA5LkQcuefjUBTktxCXUQ4rx4PcqRY1tgbSpV9eZDHWir
      address: /ip4/127.0.0.1/udp/8721/quic-v1
      public_key: 92f041e26306548444400e88eefa622dc125a45f3e3119a04ba1ffe4946dd4e6
da_network:
  backend:
    validator_settings:
      node_key: ea1e1dcc31612bd20987f017f0ca435cd2a59a4bd9fd6e14883b4803ae3b803d
      listening_address: /ip4/127.0.0.1/udp/8716/quic-v1
      policy_settings:
        min_dispersal_peers: 1
        min_replication_peers: 1
        max_dispersal_failures: 3
        max_sampling_failures: 3
        max_replication_failures: 3
        malicious_threshold: 5
      monitor_settings:
        failure_time_window: "10.0"
        time_decay_factor: "0.8"
      balancer_interval:
        secs: 5
        nanos: 0
      redial_cooldown:
        secs: 5
        nanos: 0
      replication_settings:
        seen_message_cache_size: 1000
        seen_message_ttl: "3600.0"
      subnets_settings:
        num_of_subnets: 20
        retry_limit: 5
      refresh_interval:
        secs: 30
        nanos: 0
    num_subnets: 2
  membership:
    assignations:
      - - 12D3KooWA5LkQcuefjUBTktxCXUQ4rx4PcqRY1tgbSpV9eZDHWir
        - 12D3KooWKD62Q1nAAMHeV2Cx3rNNMzjgHkTT2edFMzHZ5ur7sGnh
      - - 12D3KooWKD62Q1nAAMHeV2Cx3rNNMzjgHkTT2edFMzHZ5ur7sGnh
        - 12D3KooWA5LkQcuefjUBTktxCXUQ4rx4PcqRY1tgbSpV9eZDHWir
    subnetwork_size: 2
    dispersal_factor: 2
    addressbook:
      12D3KooWA5LkQcuefjUBTktxCXUQ4rx4PcqRY1tgbSpV9eZDHWir: /ip4/127.0.0.1/udp/8717/quic-v1/p2p/12D3KooWA5LkQcuefjUBTktxCXUQ4rx4PcqRY1tgbSpV9eZDHWir
      12D3KooWKD62Q1nAAMHeV2Cx3rNNMzjgHkTT2edFMzHZ5ur7sGnh: /ip4/127.0.0.1/udp/8716/quic-v1/p2p/12D3KooWKD62Q1nAAMHeV2Cx3rNNMzjgHkTT2edFMzHZ5ur7sGnh
da_dispersal:
  backend:
    encoder_settings:
      num_columns: 2
      with_cache: false
      global_params_path: /tmp
    dispersal_timeout: [20, 0]
    mempool_strategy:
      !SampleSubnetworks
        sample_threshold: 2
        timeout: [10, 0]
        cooldown: [0, 100]
da_indexer:
  storage:
    blob_storage_directory: ./
da_verifier:
  verifier_settings:
    sk: 67cee9fdc9c5160671b40da60b17153558496a12fb57804c1e64ef51f5a29dca
    index:
      - 1
      - 0
    global_params_path: ./tests/kzgrs/kzgrs_test_params
    domain_size: 2
  network_adapter_settings: null
  storage_adapter_settings:
    blob_storage_directory: ./
da_sampling:
  sampling_settings:
    num_samples: 1
    num_subnets: 2
    old_blobs_check_interval:
      secs: 5
      nanos: 0
    blobs_validity_duration:
      secs: 18446744073709551615
      nanos: 0
  network_adapter_settings: null
  storage_adapter_settings:
    blob_storage_directory: ./
  api_adapter_settings:
    api_port: 8722
    is_secure: false
    membership:
      assignations:
        - - 12D3KooWA5LkQcuefjUBTktxCXUQ4rx4PcqRY1tgbSpV9eZDHWir
          - 12D3KooWKD62Q1nAAMHeV2Cx3rNNMzjgHkTT2edFMzHZ5ur7sGnh
        - - 12D3KooWKD62Q1nAAMHeV2Cx3rNNMzjgHkTT2edFMzHZ5ur7sGnh
          - 12D3KooWA5LkQcuefjUBTktxCXUQ4rx4PcqRY1tgbSpV9eZDHWir
      subnetwork_size: 2
      dispersal_factor: 2
      addressbook:
        12D3KooWA5LkQcuefjUBTktxCXUQ4rx4PcqRY1tgbSpV9eZDHWir: /ip4/127.0.0.1/udp/8717/quic-v1/p2p/12D3KooWA5LkQcuefjUBTktxCXUQ4rx4PcqRY1tgbSpV9eZDHWir
        12D3KooWKD62Q1nAAMHeV2Cx3rNNMzjgHkTT2edFMzHZ5ur7sGnh: /ip4/127.0.0.1/udp/8716/quic-v1/p2p/12D3KooWKD62Q1nAAMHeV2Cx3rNNMzjgHkTT2edFMzHZ5ur7sGnh
http:
  backend_settings:
    address: 127.0.0.1:8722
    cors_origins: []
time:
  backend_settings:
    slot_config:
      slot_duration: '2.0'
      chain_start_time: [2025, 41, 9, 38, 29, 993653000, 0, 0, 0]
    epoch_config:
      epoch_stake_distribution_stabilization: 3
      epoch_period_nonce_buffer: 3
      epoch_period_nonce_stabilization: 4
    base_period_length: 11
    update_interval: [16, 0]
    ntp_server: pool.ntp.org
    ntp_client_settings:
      timeout: [5, 0]
      listening_interface: 0.0.0.0
cryptarchia:
  transaction_selector_settings: null
  blob_selector_settings: null
  config:
    epoch_config:
      epoch_stake_distribution_stabilization: 3
      epoch_period_nonce_buffer: 3
      epoch_period_nonce_stabilization: 4
    consensus_config:
      security_param: 10
      active_slot_coeff: 0.9
  genesis_id: 0x0000000000000000000000000000000000000000000000000000000000000000
  genesis_state:
    cryptarchia_ledger:
      utxos:
        utxos:
          03b2d3b8a925adcb25eb686b92db7f21a75f0e0f7c93da95b383f0fd35279e48:
            value: 1
            pk: '0000000000000000000000000000000000000000000000000000000000000000'
      nonce:
        [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
        ]
      slot: 0
      next_epoch_state:
        epoch: 1
        nonce:
          [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
          ]
        utxos:
          utxos:
            03b2d3b8a925adcb25eb686b92db7f21a75f0e0f7c93da95b383f0fd35279e48:
              value: 1
              pk: '0000000000000000000000000000000000000000000000000000000000000000'
        total_stake: 1
      epoch_state:
        epoch: 0
        nonce:
          [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
          ]
        utxos:
          utxos:
            03b2d3b8a925adcb25eb686b92db7f21a75f0e0f7c93da95b383f0fd35279e48:
              value: 1
              pk: '0000000000000000000000000000000000000000000000000000000000000000'
        total_stake: 1
    mantle_ledger: ~
  time:
    slot_duration: [2, 0]
    chain_start_time: [2025, 41, 9, 38, 29, 993653000, 0, 0, 0]
  leader_config:
    utxos:
    - tx_hash: '0000000000000000000000000000000000000000000000000000000000000000'
      output_index: 0
      note:
        value: 1
        pk: '0000000000000000000000000000000000000000000000000000000000000000'
    sk: 3cf3335017304dcfce45124a0633829f
  network_adapter_settings:
    topic: /cryptarchia/proto
  blend_adapter_settings:
    broadcast_settings:
      topic: /cryptarchia/proto
  recovery_file: ./recovery/cryptarchia.json
storage:
  db_path: nomos_db
  read_only: false
  column_family: blocks
mempool:
  cl_pool_recovery_path: ./recovery/cl_mempool.json
  da_pool_recovery_path: ./recovery/da_mempool.json
membership:
  backend:
    settings_per_service: {}
    initial_membership: {}
    initial_locators_mapping: {}
    latest_block_number: 0
sdp:
