[package]
edition = { workspace = true }
license = { workspace = true }
name    = "nomos-wallet"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
futures     = { default-features = false, version = "0.3" }
serde       = { features = ["derive"], version = "1.0" }
thiserror   = "1.0"
tokio       = { features = ["sync"], version = "1" }
tracing     = { workspace = true }

chain-service  = { workspace = true }
nomos-core     = { workspace = true }
nomos-storage  = { features = ["mock"], workspace = true }
overwatch      = { workspace = true }
services-utils = { workspace = true }
wallet         = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
# False positives.
ignored = [
  # Required by `wait_until_services_are_ready` macro.
  "futures",
]
