[package]
edition = "2021"
license = { workspace = true }
name    = "services-utils"
version = "0.1.0"

[dependencies]
async-trait = "0.1.83"
futures     = "0.3"
log         = "0.4.22"
overwatch   = { workspace = true }
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0.133"
thiserror   = "1"
tracing     = { workspace = true }

[dev-dependencies]
overwatch-derive = { workspace = true }
tokio            = { version = "1", features = ["macros"] }
tracing          = "0.1"

[package.metadata.cargo-machete]
# False positives.
ignored = [
  # Required by Overwatch's `#[derive_services]` macro.
  "tracing",
]
