[package]
edition           = "2024"
license.workspace = true
name              = "poc"
version           = "0.1.0"

[dependencies]
circuits-prover   = { workspace = true }
circuits-utils    = { workspace = true }
groth16           = { features = ["deser"], workspace = true }
num-bigint        = "0.4"
serde             = { features = ["derive"], version = "1.0" }
serde_json        = { version = "1.0" }
thiserror         = "2.0"
witness-generator = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
