[package]
edition = { workspace = true }
license = { workspace = true }
name    = "poseidon2"
version = "0.1.0"

[dependencies]
ark-bn254 = { default-features = false, features = ["scalar_field"], version = "0.4" }
ark-ff = "0.4"
jf-poseidon2 = { default-features = false, features = [
  "bn254",
], git = "https://github.com/EspressoSystems/jellyfish.git", rev = "dc166cf0f803c3e5067f9dfcc21e3dade986a447" }
num-bigint = { default-features = false, version = "0.4" }

[lints]
workspace = true
