[package]
edition           = "2024"
license.workspace = true
name              = "poseidon2"
version           = "0.1.0"

[dependencies]
ark-bn254    = "0.4"
ark-ff       = "0.4"
jf-poseidon2 = { git = "https://github.com/EspressoSystems/jellyfish.git" }
num-bigint   = "0.4"

[lints]
workspace = true
