[package]
edition = { workspace = true }
license = { workspace = true }
name    = "nomos-da-verifier"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait              = "0.1"
futures                  = { default-features = false, version = "0.3" }
kzgrs-backend            = { workspace = true }
libp2p                   = { workspace = true }
nomos-core               = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-da-network-service = { workspace = true }
nomos-da-sampling        = { workspace = true }
nomos-storage            = { workspace = true }
nomos-tracing            = { workspace = true }
nomos-utils              = { workspace = true, features = ["serde"] }
overwatch                = { workspace = true }
serde                    = { default-features = false, version = "1.0" }
serde_with               = { workspace = true }
services-utils           = { workspace = true }
subnetworks-assignations = { workspace = true }
thiserror                = "1.0"
tokio                    = { default-features = false, version = "1" }
tokio-stream             = { default-features = false, version = "0.1.15" }
tracing                  = { workspace = true }
tx-service               = { workspace = true }

[features]
libp2p          = []
rocksdb-backend = ["nomos-storage/rocksdb-backend"]
