[package]
edition = { workspace = true }
license = { workspace = true }
name    = "nomos-da-network-service"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
arc-swap    = "1"
async-trait = "0.1"
bitvec      = "1"

blake2                   = { workspace = true }
common-http-client       = { workspace = true }
futures                  = { default-features = false, version = "0.3" }
kzgrs-backend            = { workspace = true }
libp2p                   = { features = ["ed25519"], workspace = true }
libp2p-identity          = { version = "0.2" }
log                      = "0.4.22"
multiaddr                = { default-features = false, version = "0.18" }
nomos-core               = { workspace = true }
nomos-da-messages        = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-libp2p             = { workspace = true }
nomos-membership         = { workspace = true }
nomos-storage            = { workspace = true }
nomos-tracing            = { workspace = true }
nomos-utils              = { features = ["rng"], workspace = true }
overwatch                = { workspace = true }
rand                     = { workspace = true }
serde                    = { default-features = false, features = ["derive"], version = "1.0" }
services-utils           = { workspace = true }
subnetworks-assignations = { workspace = true }
thiserror                = "1"
tokio                    = { default-features = false, features = ["macros", "sync"], version = "1" }
tokio-stream             = { default-features = false, version = "0.1" }
tracing                  = { workspace = true }
url                      = { default-features = false, version = "2.5.4" }
