[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-da-network-service"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
arc-swap                 = "1"
async-trait              = "0.1"
blake2                   = { workspace = true }
common-http-client       = { workspace = true }
futures                  = "0.3"
kzgrs-backend            = { workspace = true }
libp2p                   = { workspace = true, features = ["ed25519"] }
libp2p-identity          = { version = "0.2" }
log                      = "0.4.22"
multiaddr                = "0.18"
nomos-core               = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-libp2p             = { workspace = true }
nomos-membership         = { workspace = true }
nomos-storage            = { workspace = true }
nomos-tracing            = { workspace = true }
nomos-utils              = { workspace = true, features = ["rng"] }
overwatch                = { workspace = true }
rand                     = { workspace = true }
serde                    = { version = "1.0", features = ["derive"] }
subnetworks-assignations = { workspace = true }
thiserror                = "1"
tokio                    = { version = "1", features = ["macros", "sync"] }
tokio-stream             = "0.1"
tracing                  = { workspace = true }
url                      = "2.5.4"
