on:
  schedule:
    - cron: '0 3 * * *'

  workflow_dispatch:

name: Codecov

jobs:
  test:
    env:
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: "-C instrument-coverage"
      LLVM_PROFILE_FILE: "nomos-node-%p-%m.profraw"
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
      - name: Add llvm-tools-preview component
        run: rustup component add llvm-tools-preview
      - name: Build required binaries
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72  # Version 1.0.1
        with:
          command: build
          args: --all-features -p nomos-node -p nomos-executor
      - name: Run tests
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72  # Version 1.0.1
        env:
          POL_DEV_MODE: true
          CONSENSUS_SLOT_TIME: 5
        with:
          command: test
          args: --all --all-features
      - name: Run Grcov
        run: |
          rm -rf /tmp/coverage 
          cargo binstall -y grcov;
          mkdir /tmp/coverage;
          grcov . --binary-path ./target/debug -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o /tmp/coverage/tests.lcov;
      - name: Upload integration tests results
        uses: actions/upload-artifact@6027e3dd177782cd8ab9af838c04fd81a07f1d47 # Version 4.6.2
        if: failure()
        with:
          name: integration-test-artifacts
          path: tests/.tmp*
      - name: Run codecov analysis
        uses: codecov/codecov-action@ea99328d1c4d5f39fda7cbffe104afd6906c50b0  # Version 5.4.0
        with:
          directory: /tmp/coverage/
          name: nomos-node-codecov
